FROM node:10-alpine
#FROM nodered/node-red:latest-10-minimal

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

RUN npm install node-red
# Install the dashboard extension
RUN npm install node-red-dashboard

COPY azureiotedge.js ./

USER node

CMD ["node", "azureiotedge.js"]
