FROM nodered/node-red:1.1.3-12-minimal-arm64v8

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY azureiotedge.js ./

EXPOSE 9229

USER node-red

CMD ["node", "--inspect=0.0.0.0:9229", "azureiotedge.js"]
